_target_: src.model.whisper.builders.build_whisper_model
hf_repo: ???
cache_dir: ${paths.cache_dir}/hf
# openai/whisper-tiny
# openai/whisper-base
# openai/whisper-small
# openai/whisper-medium
# openai/whisper-large-v3

output_vocabsz: ???